name: Windows

on: [push, pull_request]

jobs:
  msbuild:
    runs-on: windows-2022
    strategy:
      matrix:
        toolset: [MSVC]
        configuration: [Release]
    steps:
    - uses: actions/checkout@v4
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2
    - name: Set toolset
    - name: Build
      shell: cmd
      run: |
        msbuild Osiris.sln /p:Platform=x64 /p:Configuration=${{ matrix.configuration }} ${{ env.toolset }}
        dir /b/s *.dll

    - uses: actions/upload-artifact@v4
      with:
        path: D:\a\Osiris\Osiris\x64\Release\Osiris.dll
